### ISSUE TITLE
UAC bypasses & DLL Hijacking

### ISSUE THREAD

**Issue by nemesis7331** [cfalta/MicrosoftWontFixList#5]
Microsoft won't patch a lot of UAC bypasses, the updated list is here: https://github.com/hfiref0x/UACME
There are also some dll hijacking that microsoft won't fix, because they are not vulnerabilities (https://msrc-blog.microsoft.com/2018/04/04/triaging-a-dll-planting-vulnerability/), this is the best list I know of: https://www.wietzebeukema.nl/blog/hijacking-dlls-in-windows (it hasn't been updated in 1 year)

**Comment by cfalta** [comment]
Thank you for your feedback :-) This list was intended to be a summary of what happend in July 2021 and I decided I'll keep it that way, because I honestly think I don't have the energy to maintain an up-to-date list of ALL won't fixes Microsoft has to offer. 
I added a remark to clarify this.
