### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by binarythinktank** [cfalta/MicrosoftWontFixList#7]
should be "example" in 
A common **exampel** of target C is the LDAP service of a domain controller.

**Comment by binarythinktank** [comment]
"you're"
in
So as far as I understand, your probably stuck with SMB when it comes to servers.

**Comment by binarythinktank** [comment]
"thereon"
From thereone it's classic NTLM

**Comment by binarythinktank** [comment]
perhaps a bit pedantic but "attacker-controlled"

**Comment by binarythinktank** [comment]
tricky one to get right, for sure
"definitely"
They will definetely fix this but I guess we

**Comment by binarythinktank** [comment]
if "it is" does not sound right, it's probably "its" without the '
needs to lose it’s SYSTEM rights

**Comment by cfalta** [comment]
Wow that's a lot, thank you! I bow my head in shame ;-)
